# Generated by Django 5.2.1 on 2025-05-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiotranscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
